# Generated by Django 3.2 on 2021-09-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30000)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.test')),
            ],
        ),
    ]
